---
title: "Theme 3 Lab Notebook Volume 3"
output: html_document
---

### Description:

Date created:  9 August 2021           
Author: P. Alexander Burnham

**Summary** This document follows my progress on Theme 3 in order to provide a location for me and other members of the team to keep track of this work and maintain annotated description and functioning examples of previous iterations and related vignettes. 


### 9 August 2021:

The overall goal this week is to take the output of the rasterAlign function and write another function that creates a netcdf4 data set from it that contains all of the geospatial data and crops the data sets to the greatest common dimensions


Here I am laoding in the python version from conda
```{r setup, include=T}


#load the reticulate package  
library(reticulate)

# activate my previously created conda 3.7 environment
use_condaenv(condaenv = "Python37Env", conda = "auto", required = FALSE)


```

Make sure my 3.7 conda env is loaded
```{python}

import platform

# make sure python 3.7 is laoded
print(platform.python_version())
```

Bringing in the data and alligning the rasters with the rasterAling function
```{python}

import numpy as np
import matplotlib.pyplot as plt
import netCDF4 as nc
from rasterAlign import *


# set my absolute directory path for where the data are
direc ="/Users/pburnham/Documents/geospatialData/"

# create a list of all raster files that end in .tif
dataPaths = glob.glob(direc+"*.tif")

# call the raster align function 4326 vs 3857 nonVal SRS resolution
alignedRasters = raster_align(rastNames=dataPaths, noneVal=-1)

```

Here I am playing with some code that creates a netCDF4 data set from random datajust to see what pieces I need to pull out from the raster align output list in order to convert it to the netcdf4 format.
```{python}

# initialize file
fn = '/Users/pburnham/Documents/GitHub/Theme3_Burnham_Private/Theme3_PythonProjects/Python37Theme3/test.nc'
ds = nc.Dataset(fn, 'w', format='NETCDF4')

# inmtialize vars by creating dimensions
time = ds.createDimension('time', None) # no time var in this case
lat = ds.createDimension('lat', 10)
lon = ds.createDimension('lon', 10)


# create variables in the data set
times = ds.createVariable('time', 'f4', ('time',))
lats = ds.createVariable('lat', 'f4', ('lat',))
lons = ds.createVariable('lon', 'f4', ('lon',))
value = ds.createVariable('value', 'f4', ('time', 'lat', 'lon',))
value.units = 'My Units'

# create the main varaibles
value[0, :, :] = np.random.uniform(0, 100, size=(10, 10))  # unifrom random values

#print('var size after adding first data', value.shape)
xval = np.linspace(0.5, 5.0, 10)
yval = np.linspace(0.5, 5.0, 10)
value[1, :, :] = np.array(xval.reshape(-1, 1) + yval)  # linear gradient values

#ds.close() # cluse the dataset out in memory

```

Take a look at the dataset and add the lat and long values.
```{python}
print(ds)

# add the lat and long vals
ds.variables['lat'][:] = xval #add lat vals
ds.variables['lon'][:] = yval # add long vals

# write out data objects
lat = ds.variables['lat'][:]
lon = ds.variables['lon'][:]# matrix of longs
val = ds.variables['value'][:] 

print(val[0,:,:]) # print the values
print(lat) # print the lat
print(lon) # print the lat
```


### 10 August 2021:


Now that I know what is needed to create a netcdf4 file I can work on making extracting the necessary varaibles. First I need to make sure that the data from rasterAlign have the same bounderies. I will create a function that crops the matrices to the greatest common dimensions

```{python}

import glob
import re


# create matrix for storing corner data
cornerArray = np.empty(shape=(len(alignedRasters),4))

# loop through and extract corner data from the aligned list of rasters
for i in range(len(alignedRasters)):

    # get meta data for each raster
    meta = gdal.Info(alignedRasters[i])

    # use regex to extract upper and lower left corners
    Uleft = re.search(r'Upper Left  \(([^)]+)', meta).group(1)
    Lright = re.search(r'Lower Right \(([^)]+)', meta).group(1)

    # create full string
    corners = Uleft + ',' + Lright

    # numeric list of corners (upper left [0-1] and lower right [2-3])
    cornersList = corners.split(',')
    cornersList = [ float(x) for x in cornersList ]

    # add corners to an array
    cornerArray[i,:] = cornersList


# find greatest common dimensions to crop rasters to:
# highest x, lowest y (upper left corner): lowest x, highest y (lower right corner)
cornersCommon = [np.max(cornerArray[:,0]), np.min(cornerArray[:,1]), np.min(cornerArray[:,2]), np.max(cornerArray[:,3])]

# create the common corners
#p1 = point upper left of bounding box
#p2 = point bottom right of bounding box
p1 = (cornersCommon[0], cornersCommon[1]) 
p2 = (cornersCommon[2], cornersCommon[3]) #

```


Here is a function that trims the aligned rasters to have the same bounderies.
```{python, eval=F}
import re
import numpy as np
from osgeo import gdal

######################################################################################################################
# DESCRIPTION: raster_trim takes a list of rasters as trims them to the greatest common dimensions
# and writes out a list of numpy arrays. The last two elements in the list are the greatest common coords
# for the upper left and lower right corners and the GDAL geotransform output
#
# AUTHOR: P. Alexander Burnham
# 9 August 2021
#
# INPUTS:
# rastList (required): a list of raster objects typically already rescaled by the raster_align function.
#
# OUTPUT:
# A list of trimmed raster matrices with the last two elements as a vector of the greatest common coords
# for the upper left and lower right corners and the GDAL geotransform output vector
######################################################################################################################

def raster_trim(rastList=None):

    if rastList is None:
            print("Error: No raster list provided! Please pass raster_trim a list of rasters processed by raster_align.")
            quit() # exit program and display message when no file names provided


    outList = [] # initialize a list

    # here is where the loop needs to be:
    for i in range(len(rastList)):

        # these need to be indexed the same way
        gt = rastList[i].GetGeoTransform()
        band = rastList[i].GetRasterBand(1)

        # create matrix for storing corner data
        cornerArray = np.empty(shape=(len(rastList),4))

        # loop through and extract corner data
        for i in range(len(rastList)):

            # get meta data for each raster
            meta = gdal.Info(rastList[i])

            # use regex to extract upper and lower left corners
            Uleft = re.search(r'Upper Left  \(([^)]+)', meta).group(1)
            Lright = re.search(r'Lower Right \(([^)]+)', meta).group(1)

            # create full string
            corners = Uleft + ',' + Lright

            # numeric list of corners (upper left [0-1] and lower right [2-3])
            cornersList = corners.split(',')
            cornersList = [ float(x) for x in cornersList ]

            # add corners to an array
            cornerArray[i,:] = cornersList

        # find greatest common dimensions to crop rasters to:
        # highest x, lowest y (upper left corner): lowest x, highest y (lower right corner)
        cornersCommon = [np.max(cornerArray[:,0]), np.min(cornerArray[:,1]), np.min(cornerArray[:,2]), np.max(cornerArray[:,3])]


        #p1 = point upper left of bounding box
        #p2 = point bottom right of bounding box
        p1 = (cornersCommon[0], cornersCommon[1])
        p2 = (cornersCommon[2], cornersCommon[3])


        # get pixel sizes and the lower left of the raster
        xinit = gt[0]
        yinit = gt[3]
        xsize = gt[1]
        ysize = gt[5]

        # get row and columns
        row1 = int((p1[1] - yinit)/ysize)
        col1 = int((p1[0] - xinit)/xsize)
        row2 = int((p2[1] - yinit)/ysize)
        col2 = int((p2[0] - xinit)/xsize)

        # trim the matrix
        dataLayer = band.ReadAsArray(col1, row1, col2 - col1, row2 - row1)

        # append the data layers to the list
        outList.append(dataLayer)

        ###################################################################################################

    # add the common coords and geotransform data
    outList.append(cornersCommon)
    outList.append(gt)

    return outList

```



### 11 August 2021:

The goal is to finish the code I have been working on to create a netCDF4 cube from a set of rasters and package into functions.

This function pulls the coordinates from the aligned and trimmed rasters

```{python, eval=F}

import numpy as np
from osgeo import gdal

######################################################################################################################
# DESCRIPTION: get_coords takes in a list of trimmed raster layers from raster_trim
# and returns a list of lat and long coords
#
# AUTHOR: P. Alexander Burnham
# 10 August 2021
#
# INPUTS:
# trimmedRasts (required): a list of trimmed raster arrays from raster_trim
#
# OUTPUT:
# A list with the first element as a vector of lats and the second a vector of lons
######################################################################################################################

def get_coords(trimmedRasts=None):

    if trimmedRasts is None:
            print("Error: No raster list provided! Please pass get_coords a list of rasters processed by taster_trim.")
            quit() # exit program and display message when no file names provided

    ###################################################################################################

    outList = []

    # get the necessary structures from the object
    data = trimmedRasts[0]
    gt = trimmedRasts[-1]
    cornersCommon = trimmedRasts[-2]

    # pull out pixel size
    xsize = gt[1]
    ysize = gt[5]

    # get data mat dimensions
    width = len(data[0,:])
    height = len(data[:,0])

    # get lower left corner of clipped matrix
    ylow = cornersCommon[0]
    xlow = cornersCommon[3]

    # dimensions from 0 to max dims of dataset
    mx=np.arange(start=0, stop=width)
    my=np.arange(start=0, stop=height)

    # get lats and longs
    longVec = np.multiply(mx, xsize) + xlow # longitude vector
    latVec = np.multiply(my, ysize) + ylow # latitude vector

    outList.append(latVec)
    outList.append(longVec)

    return outList

    ###################################################################################################
```



This function takes in the coords and the trimmed and aligned rasters and writes out a netCDF4 dataset.

```{Python, eval=F}


import netCDF4 as nc
import numpy as np
from osgeo import gdal

######################################################################################################################
# DESCRIPTION: write_cube writes out a .nc file from the input of the raster_trim function and
# creates a netCDF4 dataset as a side effect
#
# AUTHOR: P. Alexander Burnham
# 11 August 2021
#
# INPUTS:
# rastList (required): a list of trimmed raster arrays from raster_trim
# yCoords: a vector for all of the y coordinates (lats)
# xCoords: a vector for all of the x coordinates (lons)
# fileName: a character string for the path and file name of the .nc file
#
# OUTPUT:
# It outputs a netCDF4 dataset and writes a .nc file to disk
######################################################################################################################

def write_cube(rastList=None, yCoords=None, xCoords=None, fileName=None):

    if rastList is None:
                print("Error: No raster list provided! Please pass write_cube a list of rasters processed by raster_trim.")
                quit() # exit program and display message when no file names provided

    data = rastList[: len(rastList) - 2]

    ds = nc.Dataset(fileName, 'w', format='NETCDF4')

    # inmtialize vars by creating dimensions (long=X)
    time = ds.createDimension('time', None) # no time var in this case
    lat = ds.createDimension('lat', len(yCoords))
    lon = ds.createDimension('lon', len(xCoords))


    # create variables in the data set
    times = ds.createVariable('time', 'f4', ('time',))
    lats = ds.createVariable('lat', 'f4', ('lat',))
    lons = ds.createVariable('lon', 'f4', ('lon',))
    value = ds.createVariable('value', 'f4', ('time', 'lat', 'lon',))
    value.units = 'My Units'

    # create the main variables
    value[0:len(data), :, :] = data

    ds.variables['lat'][:] = yCoords #add lat vals
    ds.variables['lon'][:] = xCoords # add long vals

    return ds

    ds.close() # cluse the dataset out in memory


```

Here I write up a driver to test out these function.

```{python}
import glob
import re
import numpy as np
import matplotlib.pyplot as plt
import netCDF4 as nc
from rasterAlign import *
from rasterTrim import *
from getCoords import *
from cuberator import *



# set my absolute directory path for where the data are
direc ="/Users/pburnham/Documents/geospatialData/"

# create a list of all raster files that end in .tif
dataPaths = glob.glob(direc+"*.tif")

# call the raster align function 4326 vs 3857 nonVal SRS resolution
alignedRasters = raster_align(rastNames=dataPaths, noneVal=-1)

# call the raster trim function which trims all data sets and creates list of matrices
# including the common dimensions list and the geotransform vector
trimmedRasters = raster_trim(alignedRasters)

# get x and y coordinates for the aligned and trimmed rasters
# index 0 is lat and index 1 is long
rasterCoords = get_coords(trimmedRasters)





# Write out the cube
###################################################################################################

# initialize file name
fn = '/Users/pburnham/Documents/GitHub/Theme3_Burnham_Private/Theme3_PythonProjects/Python37Theme3/test1.nc'


ds = write_cube(rastList=trimmedRasters, yCoords=rasterCoords[0], xCoords=rasterCoords[1], fileName=fn)

val = ds.variables['value'][:]
print(val[:,:,:]) # print the values



# plot to see of they are properly aligned
im = plt.imshow(val[0,:,:], cmap='hot', interpolation='nearest')
plt.show()

# plot to see of they are properly aligned
im = plt.imshow(val[1,:,:], cmap='hot', interpolation='nearest')
plt.show()


```

### 12 August 2021:

Next step, test plot the netCDF4 object on a map to make sure everything is propperly aligned.

```{python}


```

