---
title: "Theme 3 Lab Notebook Volume 2"
output: html_document
---

### Description:

Date created:  2 August 2021           
Author: P. Alexander Burnham

**Summary** This document follows my progress on Theme 3 in order to provide a location for me and other members of the team to keep track of this work and maintain annotated description and functioning examples of previous iterations and related vignettes. 


### 2 August 2021:

Here I load the GDAL library in python, read in raster files and figure out how to use the package to access the raster data.

```{r setup, include=T}


#load the reticulate package  
library(reticulate)

# activate my previously created conda 3.7 environment
use_condaenv(condaenv = "Python37Env", conda = "auto", required = FALSE)


```

Make sure my 3.7 conda env is loaded
```{python}

import platform

# make sure python 3.7 is laoded
print(platform.python_version())
```

```{python}

from osgeo import gdal
import glob
import numpy as np
import matplotlib.pyplot as plt
import time

# set my absolute directory path for where the data are
direc ="/Users/pburnham/Documents/geospatialData/"

# create a list of all raster files that end in .tif
dataPaths = glob.glob(direc+"*.tif")
print(dataPaths)

timeList = len(dataPaths) # time dimension (three times: 1980-1982 inclusive)

# create raster data set from the second file in the list
ds = gdal.Open(dataPaths[1])
print(type(ds))



# retrieving important meta data info
print(ds.RasterXSize, ds.RasterYSize) # # get dims: 29484 x 33555
print(ds.GetProjection()) # get projection info
print("number of bands:", ds.RasterCount) # there is only one band as expected
print(ds.GetGeoTransform())  # get transform data (corners)


```

Convert to an array and plot
```{python}


# pull out the band
band = ds.GetRasterBand(1)

# # convert to a large numpy array - may not be the best way to handle things
myarray = np.array(band.ReadAsArray()) #(989,335,620 points on the map)
#
#
# # plt the array as a heat map
plt.imshow(myarray, cmap='hot', interpolation='nearest')
plt.show()

```

Out of curiosity, what is the clock time for dividing a 989 million cell vectorized division process on a numpy array on my m1 macbook.
```{python}
start = time.process_time()

# divide every cell in the array by 2
x = np.divide(myarray,2)

# print the run time
print("Running time in seconds:", time.process_time() - start)




```

### 3 August 2021
Here I am attempting to pull in multiple geotiff files and create a list of gdal data sets. I will then scale them to have the same resolution and use the same coordinate systems and measurement schemes. The goal is to use meters, default to EPSG:3857 and default to the highest common scale in terms of granularity. This can be changed in the future. I will use GDAL as it seems that this is the underlying library that is used in most other python geospatial libraries.

```{python}
from osgeo import gdal
import glob
import numpy as np
import matplotlib.pyplot as plt
import time


# set my absolute directory path for where the data are
direc ="/Users/pburnham/Documents/geospatialData/"

# create a list of all raster files that end in .tif
dataPaths = glob.glob(direc+"*.tif")
#print(dataPaths)

timeList = len(dataPaths) # time dimension (three times: 1980-1982 inclusive)

# initialize a list to store files in during the loop
myDataList = [None] * timeList

# create a list of rasters
for t in range(0, timeList):
   myDataList[t] = gdal.Open(dataPaths[t])




##################################################################################################
# we have rasters of India using different coordinate systems, resulutions and slightly different cropeed frames
# here I will attempt to create a put them on a commmon coordinate system and scale

# print the transformes
print("Course Area:", myDataList[0].GetGeoTransform()) # file one us UTS scaled in degrees
print("Fine Population:", myDataList[1].GetGeoTransform()) # file two is using meters

# get projection info
print("Course Area:", myDataList[0].GetProjection())
print("Fine Population:", myDataList[1].GetProjection())


# initialize a list to store altered files
myDataListScaled = [None] * timeList

# create a list of rasters rescaled to EPSG:3857 with a common grid size
# the resulutions are hard-coded here. Will add flexability nect by picking max dim of all imported rasters
for t in range(0, timeList):
   myDataListScaled[t] = gdal.Warp('', myDataList[t], dstSRS='EPSG:3857', format='VRT',
   outputType=gdal.GDT_Int16,xRes=1052.2047247721555, yRes=-1052.2047247721555)

# reprint the transformes after allteration
print("Course Area:", myDataListScaled[0].GetGeoTransform()) # file one us UTS scaled in degrees
print("Fine Population:", myDataListScaled[1].GetGeoTransform()) # file two is using meters

```

Here I scale down and make sure non data values are consitant and specified so they are not used in interpolation. Scaling down makes it easier to see what is going on
```{python}

############################################################################################################
# the overall layer sizes are different but the actual data the rasters are aligned now. Next we have to figure out how
# to write them into a netcdf4 array still aligned with eachother.
# what to do about missing data and overlap is still a question of importance force -9999 as missing data as default
# we can make this a user input


# specifying targetAlignedPixels=True aligns pixels by coordinate system adn scaling down to make sure things are working 
# adding missing data arguemnet
for t in range(0, timeList):
   myDataListScaled[t] = gdal.Warp('', myDataList[t], targetAlignedPixels=True, dstSRS='EPSG:3857', format='VRT',
   outputType=gdal.GDT_Int16,xRes=200000, yRes=-200000, dstNodata=-9999, outputBounds="maxY")


print(gdal.Info(myDataListScaled[0]))
print(gdal.Info(myDataListScaled[1]))

# pull out the bands
band = myDataListScaled[0].GetRasterBand(1)
band1 = myDataListScaled[1].GetRasterBand(1)

# # convert to a numpy array - may not be the best way to handle things
myarray = np.array(band.ReadAsArray())
myarray1 = np.array(band1.ReadAsArray())

# print the arrays
print(myarray)
print(myarray1)

# # plt the array as a heat map
plt.imshow(myarray, cmap='hot', interpolation='nearest')

plt.show()

# # plt the array as a heat map
plt.imshow(myarray1, cmap='hot', interpolation='nearest')
plt.show()

```

### 5 August 2021
Here I create a function that pulls in raster file names and returns a list of geospatially aligned raster objects of the same type
```{python, eval=FALSE}

from osgeo import gdal
import glob
import numpy as np

#############################################################################################################
# DESCRIPTION: This function called raster_align takes a list of raster names, loads the rasters
# into memory and ensures they have the same aligned structure with the correct SRS codes and consitant resolutions
#
# AUTHOR: P. Alexander Burnham
# 5 August 2021
#
# INPUTS:
# rastNames (required): a list or array of file names including the required path if in another directory.
# resolution: the pixel dimensions to be used for all rasters. Defaults to the largest common pixel size
# SRS: this is the SRS code that sets the units and geospatial scale. Defaults to EPSG:3857 like google maps
# noneVal: the value to be used for pixels in the raster that contain no value. Defaults to -9999
#
# OUTPUT:
# It outputs a list of rescaled and gepspatialy aligned rasters
#############################################################################################################
def raster_align(rastNames=None, resolution=None, SRS=3857, noneVal=-9999):

    if rastNames is None:
        print("Error: No file list provided! Please pass raster_align a list of raster file names.")
        quit() # exit program and display message when no file names provided

    # define the espg code as a character for GDAL
    SRS_code = "EPSG:" + str(SRS)

    timeList = len(rastNames) # time dimension for list

    # initialize a mat to store files in during the loop and one to store the modification
    dataMat = [[0] * 3 for i in range(timeList)]

    # create a list of rasters in first column
    for t in range(0, timeList):
        dataMat[0][t] = gdal.Open(rastNames[t])

    # if resolution is not provided, default to the greatest common resolution
    if resolution is None:
        # get greatest common dimension
        for j in range(0, timeList):

            # put on same scale based on the SRS code to get consistant resolution values
            temp = gdal.Warp('', dataMat[0][j], dstSRS=SRS_code, format='VRT')
            dataMat[1][j] = temp.GetGeoTransform()[1]

        temp=None # flush from disk

        # get max resolution value
        resolution = np.max(dataMat[1][:])

    # do transformation and alingnment
    for i in range(0, timeList):
        dataMat[2][i] = gdal.Warp('', dataMat[0][i], targetAlignedPixels=True, dstSRS=SRS_code, format='VRT',
        outputType=gdal.GDT_Int16, xRes=resolution, yRes=-resolution, dstNodata=noneVal)

    return dataMat[2][:]
#############################################################################################################
# END FUNCTION
#############################################################################################################


```

Here is a driver that calls this function as an example.

```{python}
import glob
import numpy as np
import matplotlib.pyplot as plt
import netCDF4 as nc
from rasterAlign import *


# set my absolute directory path for where the data are
direc ="/Users/pburnham/Documents/geospatialData/"

# create a list of all raster files that end in .tif
dataPaths = glob.glob(direc+"*.tif")


# call the raster align function
alignedRasters = raster_align(rastNames=dataPaths)

# print the origins and pixel sizes for all three files after the transform
print(alignedRasters[0].GetGeoTransform(1))
print(alignedRasters[1].GetGeoTransform(1))
print(alignedRasters[2].GetGeoTransform(1))


# Specify srs 4326 vs 3857
alignedRastersCustom = raster_align(rastNames=dataPaths, noneVal=-9999, SRS=4326)

print(alignedRastersCustom[0].GetGeoTransform(1))
print(alignedRastersCustom[1].GetGeoTransform(1))
print(alignedRastersCustom[2].GetGeoTransform(1))


# 3857 with a large pixel size
alignedRastersDims = raster_align(rastNames=dataPaths, noneVal=-0, resolution=10000)

print(alignedRastersDims[0].GetGeoTransform(1))
print(alignedRastersDims[1].GetGeoTransform(1))
print(alignedRastersDims[2].GetGeoTransform(1))

ds = alignedRastersDims[0].ReadAsArray()
im = plt.imshow(ds, cmap='hot', interpolation='nearest')
plt.show()

ds1 = alignedRastersDims[1].ReadAsArray()
im1 = plt.imshow(ds1, cmap='hot', interpolation='nearest')
plt.show()
```
